# Generated by Django 5.1.7 on 2025-03-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artillerysettings',
            options={'verbose_name_plural': 'Settings'},
        ),
    ]
