# Generated by Django 5.1.7 on 2025-03-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_artillerysettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artillerysettings',
            name='bullet_speed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
