# Generated by Django 5.1.7 on 2025-04-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_artillerysettings_bullet_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='artillerysettings',
            name='max_angle',
            field=models.DecimalField(decimal_places=1, default=90, max_digits=3),
        ),
        migrations.AddField(
            model_name='artillerysettings',
            name='min_angle',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='artillerysettings',
            name='bullet_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artillerysettings',
            name='max_distance',
            field=models.JSONField(default=0),
        ),
    ]
