# Generated by Django 5.1.7 on 2025-04-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_artillerysettings_max_angle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artillerysettings',
            name='max_distance',
            field=models.JSONField(default='{}'),
        ),
    ]
