# Generated by Django 5.1.7 on 2025-04-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_artillerysettings_max_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artillerysettings',
            name='max_distance',
            field=models.JSONField(default=''),
        ),
    ]
